env: "gymma"

env_args:
  key: null
  time_limit: 25
  pretrained_wrapper: null

test_greedy: True
test_nepisode: 50
test_interval: 20_000
log_interval: 20_000
runner_log_interval: 20_000
learner_log_interval: 20_000
# t_max: 2050000
